%% IMPROVED PRESENTATION OF FURTHER INVESTIGATIONS OF HYPOTHESES - REVISIONS FALL 2018
% uses the results generated by try_script_hyp_nov9.m

close all; clearvars; clc;

N_Drug_Hyp = 2; % Number of treatment conditions for which we further examine hypotheses (Tram. or Comb.)
N_CON = 2;      % # constraint options (default constraints or extra constraints)
                                                  
Mcell = cell(N_Drug_Hyp, 1);
% Mcell{1} = 4-well test data tram
% Mcell{2} = 4-well test data comb
        % |---k=1=0h----| ... |----k=6=60h----|
        % well 1 -> well 4 ... well 1 -> well 4
        
MHATcell = cell(N_Drug_Hyp, N_CON);
% MHATcell{1}{1} = prediction matrix using A*(15-well, default constraints) tram
% MHATcell{2}{1} = prediction matrix using A*(15-well, default constraints) comb
% MHATcell{1}{2} = prediction matrix using A*(15-well, extra constraints) tram
% MHATcell{2}{2} = prediction matrix using A*(15-well, extra constraints) comb
             % |---k=2=12h----| ... |----k=7=72h----|
             % well 1 -> well 4 ... well 1 -> well 4

%% PART 1: Form Mcell and MHATcell
for aa = 1 : N_Drug_Hyp
    
    if aa == 1 % Tram. 
        load('Trying_Out_Hyp_Results_Fall2017\try_tram_enrich_nov9.mat');
    elseif aa == 2 % Comb.
        clearvars -except N_Drug_Hyp N_CON Mcell MHATcell aa
        load('Trying_Out_Hyp_Results_Fall2017\try_comb_derich_nov9.mat');
    end
    
    for c = 1 : N_CON
        % model w/ extra constraints        model w/default constraints
        if c == 2, myA = A_extracon; elseif c == 1, myA = A_STAR{drug}; end
                                                  
        MHATcell{aa}{c} = myA * M; % 12h -> 72h predictions
        
    end
    Mcell{aa} = M; % 0h -> 60h test data
    
end

%% PART 2: Compute p-values and upper/lower prediction curves    

clearvars -except N_Drug_Hyp N_CON Mcell MHATcell N_W STATE
N_STATE = length(STATE); LIGHT_PINK = [255/255 153/255 255/255];
time_horizon_samp = 0:12:60; N_T = 6;    % # time points in Mcell{aa}, in data sample horizon
time_horizon_pred = 0:12:72; N_TIME = 7; % # time points in prediction horizon
predState = cell(N_Drug_Hyp, N_CON); pvals = cell(N_Drug_Hyp, N_CON);
curveUP = cell(N_Drug_Hyp, N_CON); curveMI = cell(N_Drug_Hyp, N_CON); curveLO = cell(N_Drug_Hyp, N_CON);                                                  
K0 = 2; % get p-value for time horizon k=2=12h->N_T=6=60h (initial conditions for predictions & data samples are equal)

for aa = 1 : N_Drug_Hyp
    
    for c = 1 : N_CON
                                                %0h                      12h->72h
        predState{aa}{c} = getPredCellONEMODEL( Mcell{aa}(:,1:N_W), N_W, MHATcell{aa}{c}, N_TIME, N_STATE );
        % predState{aa}{c}{i}{k} = row vector of one-step predictions of #cells(state i, time k) using [Mcell{aa}(:,1:N_W), MHATcell{aa}{c}]
        % k = 1 is 0h, k = 2 is 12h, ..., k = 7 is 72h
    
        pvals{aa}{c} = getPredvsSampSTAT( predState{aa}{c}, Mcell{aa}, N_W, N_T, N_STATE, K0 ); 
        % pvals{aa}{c}{i} = p-value, one-step predictions versus data samples (state i, agent a) over time k=K0=2 to N_T
        %                   via 2-way analysis of variance (ANOVA)
        
        [curveUP{aa}{c}, curveMI{aa}{c}, curveLO{aa}{c}] = getPredULBandONEMODEL( predState{aa}{c}, N_TIME, N_STATE );
        % curveUP{aa}{c}{i}(k) = maximum of predState{aa}{c}{i}{k}
        % curveMI{aa}{c}{i}(k) = median of predState{aa}{c}{i}{k}
        % curveLO{aa}{c}{i}(k) = minimum of predState{aa}{c}{i}{k}
    end
    
end

%% PART 3: Plot test data samples and prediction curves
% [1: Tram (aa=1), default constraints (c=1)] [2: Tram (aa=1), extra constraints (c=2)]
% [3: Comb (aa=2), default constraints (c=1)] [4: Comb (aa=2), extra constraints (c=2)]
figure; FigureSettings;

for aa = 1 : N_Drug_Hyp
    
    if aa == 1 % Tram. hyp: state of interest is K14hi = 1st element in state vector
        mystate = 1; myylabel = 'Tram., # K14^{hi} live cells';  
    elseif aa == 2 % Comb. hyp: state of interest is VIMhiK14low = 2nd element in state vector
        mystate = 2; myylabel = 'Comb., # VIM^{hi}K14^{low} live cells';
    end
    
    for c = 1 : N_CON
         % default constraints                      extra constraints
        if c==1, mytitle = 'Original model'; elseif c==2, mytitle = 'Further constrained model'; end
        
        subplot(N_Drug_Hyp, N_CON, (aa-1)*N_CON + c );
        
        % plot upper/lower prediction band: max, median, min at each time point
        plotBandENSEMBLE( curveUP{aa}{c}{mystate}, curveMI{aa}{c}{mystate}, curveLO{aa}{c}{mystate}, time_horizon_pred, LIGHT_PINK );
        
        % plot individual predictions (red stars)
        %for k = 2 : N_TIME, plot( time_horizon_pred(k)*ones(N_W,1), MHATcell{aa}{c}(mystate,(k-2)*N_W+1:(k-1)*N_W), '*r', 'linewidth', 1 ); hold on; end
   
        % plot data samples (black stars)
        plotDataSampENSEMBLE( Mcell{aa}(mystate,:), N_W, N_T, time_horizon_samp );
        
        myp = pvals{aa}{c}{mystate}; % p-value, drug_for_hyp aa, constraint type c, state mystate
        
        if myp < 0.001, mypstr = 'p < 0.001';   % reporting convention
        elseif myp > 0.99, mypstr = 'p > 0.99'; % reporting convention
        else, mypstr = ['p = ', num2str( round(myp, 2, 'significant') )]; % rounded to 2 significant digits
        end
        
        % to put text in legend without marker (from MATLAB Answers(TM), Walter Roberson, 21 Apr 2018)
        dummyh = line(nan, nan, 'Linestyle', 'none', 'Marker', 'none', 'Color', 'none');
        legend(dummyh, mypstr, 'Location', 'best');
        legend boxoff % Hides the legend's axes (legend border and background)
        
        title(mytitle); xlabel('time (h)'); ylabel(myylabel); xlim([min(time_horizon_pred) max(time_horizon_pred)]);
        if aa==2, ylim([200 600]); end; % so that Comb. comparisons are on same scale
    
    end
    
end


                   
